### ISSUE TITLE
Lien avec le projet dbnomics

### ISSUE THREAD

**Issue by pachevalier** [RLesur/inseex#1]
Je viens d'apercevoir ton projet en me connectant à Github.

Je pense qu'il y a potentiellement un doublon avec le projet [DBnomics](https://next.nomics.world/) du CEPREMAP. 

Leur plateforme agrège notamment les données SDMX de l'INSEE et permet d'y accéder directement via des clients Python et R : 

- https://git.nomics.world/dbnomics/rdbnomics#dbnomics-r-client

**Comment by RLesur** [comment]
Tu es rapide ! je viens à peine de créer le repo... je comptais me remettre effectivement au service SDMX de l'Insee. Tu fais bien de me prévenir. Je vais jeter un coup d'oeil à DBnomics.
Merci !
